<CalculatorWidget>:
    BoxLayout:
        size: root.size
        orientation: "vertical"
        size_hint_y: 1
        spacing: 1

        TextInput:
            multiline: False
            focus: True
            size_hint_y: 0.3
            halign: "right"
            valign: "bottom"
            padding: "10dp"
            background_color: 36/255, 38/255, 42/255, 1
            background_normal: '' # Remove the default background
            background_down: ''
            background_active: ''
            foreground_color: 1, 1, 1, 1
            allow_copy: False
            cursor_color: 1, 1, 1, 1
            cursor_blink: True
            cursor_width: "5dp"
            hint_text: "0"
            input_filter: "float"
            line_height: "15dp"
            font_size: "45dp"
            font_name: "./fonts/Poppins-MediumItalic.ttf"
        
        GridLayout:
            cols: 4
            rows: 3
            size_hint_y: 0.42
            spacing: 1

            # Row 1

            Button:
                text: "AC"
                background_color: 36/255, 38/255, 42/255, 1
                background_normal: '' # Remove the default background
                background_down: ''
                color: 234/255, 122/255, 244/255, .6

            Button:
                text: "÷"
                background_color: 36/255, 38/255, 42/255, 1
                background_normal: '' # Remove the default background
                background_down: ''
                font_size: "25dp"
                color: 234/255, 122/255, 244/255, .6

            Button:
                text: "x"
                background_color: 36/255, 38/255, 42/255, 1
                background_normal: '' # Remove the default background
                background_down: ''
                font_size: "20dp"
                color: 234/255, 122/255, 244/255, .6

            Button:
                text: "DEL"
                background_color: 234/255, 122/255, 244/255, 1
                background_normal: '' # Remove the default background
                background_down: ''
                color: 1, 1, 1, 0.6

            # Row 2

            Button:
                text: "7"
                background_color: 36/255, 38/255, 42/255, 1
                background_normal: '' # Remove the default background
                background_down: ''
                font_size: "20dp"
                color: 1, 1, 1, 0.6

            Button:
                text: "8"
                background_color: 36/255, 38/255, 42/255, 1
                background_normal: '' # Remove the default background
                background_down: ''
                font_size: "20dp"
                color: 1, 1, 1, 0.6

            Button:
                text: "9"
                background_color: 36/255, 38/255, 42/255, 1
                background_normal: '' # Remove the default background
                background_down: ''
                font_size: "20dp"
                color: 1, 1, 1, 0.6

            Button:
                text: "-"
                background_color: 234/255, 122/255, 244/255, 1
                background_normal: '' # Remove the default background
                background_down: ''
                font_size: "30dp"
                color: 1, 1, 1, 0.6

            # Row 3

            Button:
                text: "4"
                background_color: 36/255, 38/255, 42/255, 1
                background_normal: '' # Remove the default background
                background_down: ''
                font_size: "20dp"
                color: 1, 1, 1, 0.6

            Button:
                text: "5"
                background_color: 36/255, 38/255, 42/255, 1
                background_normal: '' # Remove the default background
                background_down: ''
                font_size: "20dp"
                color: 1, 1, 1, 0.6

            Button:
                text: "6"
                background_color: 36/255, 38/255, 42/255, 1
                background_normal: '' # Remove the default background
                background_down: ''
                font_size: "20dp"
                color: 1, 1, 1, 0.6

            Button:
                text: "+"
                background_color: 234/255, 122/255, 244/255, 1
                background_normal: '' # Remove the default background
                background_down: ''
                font_size: "25dp"
                color: 1, 1, 1, 0.6

        BoxLayout:
            size_hint_y: 0.28
            spacing: 1
            
            GridLayout:
                cols: 3
                rows: 2
                size_hint_x: 0.75
                spacing: 1

                # Row 1

                Button:
                    text: "1"
                    background_color: 36/255, 38/255, 42/255, 1
                    background_normal: '' # Remove the default background
                    background_down: ''
                    font_size: "20dp"
                    color: 1, 1, 1, 0.6

                Button:
                    text: "2"
                    background_color: 36/255, 38/255, 42/255, 1
                    background_normal: '' # Remove the default background
                    background_down: ''
                    font_size: "20dp"
                    color: 1, 1, 1, 0.6

                Button:
                    text: "3"
                    background_color: 36/255, 38/255, 42/255, 1
                    background_normal: '' # Remove the default background
                    background_down: ''
                    font_size: "20dp"
                    color: 1, 1, 1, 0.6

                # Row 2

                Button:
                    text: "."
                    background_color: 36/255, 38/255, 42/255, 1
                    background_normal: '' # Remove the default background
                    background_down: ''
                    font_size: "50dp"
                    valign: "center"
                    halign: "center"
                    color: 1, 1, 1, 0.6

                Button:
                    text: "0"
                    background_color: 36/255, 38/255, 42/255, 1
                    background_normal: '' # Remove the default background
                    background_down: ''
                    font_size: "20dp"
                    color: 1, 1, 1, 0.6

                Button:
                    text: "%"
                    background_color: 36/255, 38/255, 42/255, 1
                    background_normal: '' # Remove the default background
                    background_down: ''
                    font_size: "20dp"
                    color: 1, 1, 1, 0.6

            Button:
                size_hint_x: 0.25
                text: "="
                background_color: 234/255, 122/255, 244/255, 1
                background_normal: '' # Remove the default background
                background_down: ''
                font_size: "25dp"
                color: 1, 1, 1, 0.6
                
